<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Focus-QA-4" name="com.focus.testcases.RestoreCompanyTest" tests="16" failures="2" timestamp="5 Dec 2019 14:42:36 GMT" time="199.822" errors="0">
  <testcase name="checkSignInBtToCheckRestoreNoWithValidUserNameAndValidPassword" time="33.743" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkCloseBtnInDataStatistics" time="2.983" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkSignOut" time="1.840" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkClickOnNoButtonInRestoreCompany" time="36.930" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkClickOnRestoreCompanyWithoutPath" time="0.795" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkSignInBtToCheckRestoreYesWithValidUserNameAndValidPassword" time="29.634" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkDatatStatisticsInCompanyBackupRestoreWithYesOption" time="4.682" classname="com.focus.testcases.RestoreCompanyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.RestoreCompanyTest.checkDatatStatisticsInCompanyBackupRestoreWithYesOption(RestoreCompanyTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkDatatStatisticsInCompanyBackupRestoreWithYesOption -->
  <testcase name="checkDatatStatisticsInCompanyBackupRestoreWithNoOption" time="4.855" classname="com.focus.testcases.RestoreCompanyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.RestoreCompanyTest.checkDatatStatisticsInCompanyBackupRestoreWithNoOption(RestoreCompanyTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkDatatStatisticsInCompanyBackupRestoreWithNoOption -->
  <testcase name="checkCompanyRestoreCompanyCodeIsDisplayInCompanyList" time="12.039" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkClickOnYesButtonInRestoreCompany" time="35.374" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkClickOnRestoreCompanyOnSelectingPath" time="5.821" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkLoginButtonInAdminCredentialsByInputUserNameAndPassword" time="3.131" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkCloseBtnInDataStatisticsCompanyWithNoOption" time="3.018" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkClickOnBrowseBtnAndSelectBackupInRestoreCompany" time="10.911" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkAdminCredentialsScreenOnClickOnRestoreOptionInLoginPage" time="8.150" classname="com.focus.testcases.RestoreCompanyTest"/>
  <testcase name="checkClickOnCancelButtonInRestoreCompany" time="5.916" classname="com.focus.testcases.RestoreCompanyTest"/>
</testsuite> <!-- com.focus.testcases.RestoreCompanyTest -->
